### ISSUE TITLE
IncompatibleClassChangeError ... Found interface ... PyRequirement but class was expected

### ISSUE THREAD

**Issue by mcstafford-git** [alexmojaki/birdseye-pycharm#2]
* pycharm-community-2018.2.3
* birdseye-pycharm version 1.0
* Python 3.6.6
* Debian 10/Buster
* openjdk 10.0.2 2018-07-17
* OpenJDK Runtime Environment (build 10.0.2+13-Debian-1)
* OpenJDK 64-Bit Server VM (build 10.0.2+13-Debian-1, mixed mode)

Haven't previously installed a plugin, used: File > Settings > Plugins > Browse repositories.

[stacktrace-0.txt](https://github.com/alexmojaki/birdseye-pycharm/files/2386008/stacktrace-0.txt)

edit: added java info

**Comment by above-c-level** [comment]
I'm getting an exception thrown which is very similar to the above. 
[Here's the stacktrace.](https://github.com/alexmojaki/birdseye-pycharm/files/2386295/stacktrace.txt)

Also, I'm using:
- PyCharm Professional 2018.2.3
- Anaconda 4.5.4
- Python 3.6.5
- Windows 10

I'm using Birdseye-PyCharm 1.0. Will try installing from disk after pulling from github since version 1.0.1 is pending approval from JetBrains.

**Comment by alexmojaki** [comment]
Thanks for the bug reports. 1.0.1 is now approved so I consider this particular issue fixed.

@above-c-level I thought that PyCharm would install things only via pip, hence those arguments. Wasn't expecting conda to be used sometimes. Not sure how to deal with that, probably need to open a new issue. However I don't really understand what happened, can you elaborate? If pip installed the most recent version, wasn't the problem sorted then? Is conda not able to recognise packages installed by pip? I don't expect separately installing via pip to make the balloon automatically disappear.

**Comment by above-c-level** [comment]
@alexmojaki I can see how that might have been confusing without some extra details. I'll try to answer the questions you raised (with pictures if possible, also note that it might be a little *too* detailed).

I run everything through anaconda environments. My main env I named tensorflow (back when I first started getting into ml, it's grown massively since then and I've kept the name through various installs). My guess is that when PyCharm recognizes that you're using an anaconda environment, it assumes that it should install packages using the conda command (which I'm assuming is triggered by ["this::start" on line 112 of ProcessMonitor.java](https://github.com/alexmojaki/birdseye-pycharm/blob/e762fc9c2ec7ecab731c3e59c00aede93131d7a0/src/com/github/alexmojaki/birdseye/pycharm/ProcessMonitor.java#L112)

Anyway, PyCharm was attempting to install birdseye with conda, we know that much is certain. I attempted to fix the commands that were being given to conda to see if maybe it was just adding args that weren't intended for conda usage. However, birdseye doesn't exist in any of the anaconda repositories, so the result was conda saying exactly that.
![conda install birdseye in cmd](https://user-images.githubusercontent.com/33842389/45931401-131d8200-bf2b-11e8-9e50-e5f55d1449c4.PNG)

After that, I attempted to uninstall and reinstall using pip.
![pip reinstalling birdseye](https://user-images.githubusercontent.com/33842389/45931523-60e6ba00-bf2c-11e8-8ea1-ad04eb4b4ea3.PNG) The installation was successful, though as is evident from the last part of edit 1, PyCharm was still having issues recognizing it. Conda is able to recognize packages installed via pip, as can be demonstrated when invoking python from the command line
![python running birdseye](https://user-images.githubusercontent.com/33842389/45931554-dbafd500-bf2c-11e8-9627-ec03637ce4c6.PNG)

I can still reproduce the issue in PyCharm actually. Despite having the package installed on my computer, it won't recognize it in a new project yet.
![pycharm not recognizing](https://user-images.githubusercontent.com/33842389/45931595-5e389480-bf2d-11e8-96d7-9fad7238c516.PNG)
Clicking _here_ results in 
![failed](https://user-images.githubusercontent.com/33842389/45931633-e028bd80-bf2d-11e8-925a-e9526d5ccf3d.PNG) 
and clicking on *details...* from there yields
![details](https://user-images.githubusercontent.com/33842389/45931637-e880f880-bf2d-11e8-83b0-fe8dc9c0eb0a.PNG)

In the end, the reason why PyCharm wasn't recognizing birdseye is that I believe the conda package manager only keeps track of things installed via "conda install x", so disabling it in PyCharm is what allowed birdseye-pycharm to function correctly.
![conda package manager](https://user-images.githubusercontent.com/33842389/45931717-f6834900-bf2e-11e8-990b-860d78fcb5fc.PNG)
